apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartnms
  namespace: smartnms
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  tls:
    - hosts:
        - smartnms.example.com
      secretName: smartnms-tls
  rules:
    - host: smartnms.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: smartnms-backend
                port:
                  number: 5000
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: smartnms-backend
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smartnms-frontend
                port:
                  number: 5173
